{
 "title": "prédictions ML",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": " CPU par container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{name=~\"accidents.*\"}[5m]) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "erreurs HTTP par type ",
   "type": "barchart",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (error_type) (http_errors_total)",
     "legendFormat": "{{error_type}}"
    }
   ]
  },
  {
   "title": "probabilité moyenne des graves",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 4, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prediction_probability_sum{gravite=\"Grave\"} / prediction_probability_count{gravite=\"Grave\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "latence du modèle ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(model_inference_duration_seconds_sum[5m]) / rate(model_inference_duration_seconds_count[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "total des prédictions ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 11, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(prediction_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "prédiction par gravité ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "predictions/sec" } },
   "targets": [
    { "expr": "rate(prediction_total[5m])", "legendFormat": "{{gravite}}" }
   ]
  }
 ]
}